export const types = {
  CASE_STORY_CYCLE: 'CASE_STORY_CYCLE',
  CONTACT_FORM_SUBMIT: 'CONTACT_FORM_SUBMIT',
  HERO_CYCLE: 'HERO_CYCLE',
  NEWSLETTER_FORM_SUBMIT: 'NEWSLETTER_FORM_SUBMIT',
  SET_ACTIVE_SECTION: 'SET_ACTIVE_SECTION',
  SET_ACTIVE_SOLUTION: 'SET_ACTIVE_SOLUTION',
  SET_ACTIVE_SUBTAB: 'SET_ACTIVE_SUBTAB',
  SET_ACTIVE_STORY: 'SET_ACTIVE_STORY',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_EXPANDED_STORY: 'SET_EXPANDED_STORY',
  SET_LIST_OPEN_CLOSE: 'SET_LIST_OPEN_CLOSE',
  SET_MENU: 'SET_MENU',
  SET_MOBILE_CASE: 'SET_MOBILE_CASE',
  SET_HERO_SLIDE: 'SET_HERO_SLIDE',
  SET_SELECTED_STORY: 'SET_SELECTED_STORY',
  SET_SELECTOR_POSITION: 'SET_SELECTOR_POSITION',
  SET_SELECTOR_WIDTH: 'SET_SELECTOR_WIDTH'
}