export const types = {
  CASE_STORY_CYCLE: 'CASE_STORY_CYCLE',
  SELECTED_STORY: 'SELECTED_STORY',
  SET_ACTIVE_SECTION: 'SET_ACTIVE_SECTION',
  SET_ACTIVE_STORY: 'SET_ACTIVE_STORY',
  SET_MENU: 'SET_MENU',
  SET_HERO_SLIDE: 'SET_HERO_SLIDE',
  SET_SELECTOR_POSITION: 'SET_SELECTOR_POSITION',
  SET_SELECTOR_WIDTH: 'SET_SELECTOR_WIDTH'
}